[rospy.client][INFO] 2020-11-28 06:13:00,896: init_node, name[/train_11191_1606543980867], pid[11191]
[xmlrpc][INFO] 2020-11-28 06:13:00,896: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-28 06:13:00,897: Started XML-RPC server [http://192.168.0.191:43017/]
[rospy.init][INFO] 2020-11-28 06:13:00,897: ROS Slave URI: [http://192.168.0.191:43017/]
[rospy.impl.masterslave][INFO] 2020-11-28 06:13:00,898: _ready: http://192.168.0.191:43017/
[rospy.registration][INFO] 2020-11-28 06:13:00,899: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-11-28 06:13:00,899: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-11-28 06:13:00,998: registered with master
[rospy.rosout][INFO] 2020-11-28 06:13:00,998: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-28 06:13:01,004: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-28 06:13:01,005: initializing /clock core topic
[rospy.simtime][INFO] 2020-11-28 06:13:01,009: connected to core topic /clock
[rospy.internal][INFO] 2020-11-28 06:13:01,012: topic[/clock] adding connection to [http://192.168.0.201:33661/], count 0
[rospy.internal][INFO] 2020-11-28 06:13:01,029: topic[/start_goal_points] adding connection to [http://192.168.0.201:46391/], count 0
[rospy.internal][INFO] 2020-11-28 06:13:01,034: topic[/scan] adding connection to [http://192.168.0.201:33661/], count 0
[rospy.internal][INFO] 2020-11-28 06:13:01,041: topic[/is_start_episode] adding connection to [http://192.168.0.201:39437/], count 0
[rospy.internal][INFO] 2020-11-28 06:13:01,044: topic[/odom] adding connection to [http://192.168.0.201:33661/], count 0
[rospy.internal][INFO] 2020-11-28 06:13:01,178: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-11-28 06:13:01,184: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.internal][INFO] 2020-11-28 06:13:01,281: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-28 06:13:09,792: topic[/scan] adding connection to [http://192.168.0.201:34917/], count 1
[rospy.internal][INFO] 2020-11-28 06:13:09,799: topic[/bev/flow_image] adding connection to [http://192.168.0.201:34067/], count 0
[rospy.internal][INFO] 2020-11-28 06:13:09,801: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:34067/], count 0
[rospy.internal][INFO] 2020-11-28 06:13:09,880: topic[/cmd_vel] adding connection to [/bev_flow_estimator], count 1
[rospy.core][INFO] 2020-11-28 06:13:32,800: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-11-28 06:13:32,810: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-28 06:13:32,810: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-11-28 06:13:32,811: topic[/cmd_vel] removing connection to /bev_flow_estimator
[rospy.internal][INFO] 2020-11-28 06:13:32,811: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2020-11-28 06:13:32,812: topic[/clock] removing connection to http://192.168.0.201:33661/
[rospy.internal][INFO] 2020-11-28 06:13:32,812: topic[/bev/flow_image] removing connection to http://192.168.0.201:34067/
[rospy.internal][INFO] 2020-11-28 06:13:32,813: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:34067/
[rospy.internal][INFO] 2020-11-28 06:13:32,814: topic[/odom] removing connection to http://192.168.0.201:33661/
[rospy.internal][WARNING] 2020-11-28 06:13:32,815: Unknown error initiating TCP/IP socket to 192.168.0.201:52767 (http://192.168.0.201:33661/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-11-28 06:13:32,815: topic[/start_goal_points] removing connection to http://192.168.0.201:46391/
[rospy.internal][WARNING] 2020-11-28 06:13:32,816: Unknown error initiating TCP/IP socket to 192.168.0.201:52767 (http://192.168.0.201:33661/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-11-28 06:13:32,817: Unknown error initiating TCP/IP socket to 192.168.0.201:60799 (http://192.168.0.201:46391/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2020-11-28 06:13:32,818: Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 846, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2020-11-28 06:13:32,818: topic[/scan] removing connection to http://192.168.0.201:33661/
[rospy.internal][INFO] 2020-11-28 06:13:32,818: topic[/scan] removing connection to http://192.168.0.201:34917/
[rospy.internal][INFO] 2020-11-28 06:13:32,819: topic[/is_start_episode] removing connection to http://192.168.0.201:39437/
[rospy.impl.masterslave][INFO] 2020-11-28 06:13:32,819: signal-2
[rospy.internal][WARNING] 2020-11-28 06:13:32,820: Unknown error initiating TCP/IP socket to 192.168.0.201:38829 (http://192.168.0.201:34917/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-11-28 06:13:33,299: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-28 06:13:33,343: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-28 06:13:33,361: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-28 06:13:33,396: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-28 06:13:33,405: signal_shutdown [atexit]
