[rospy.client][INFO] 2020-11-24 03:31:49,745: init_node, name[/train_2950_1606188709712], pid[2950]
[xmlrpc][INFO] 2020-11-24 03:31:49,746: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-24 03:31:49,747: Started XML-RPC server [http://192.168.0.191:41825/]
[rospy.init][INFO] 2020-11-24 03:31:49,747: ROS Slave URI: [http://192.168.0.191:41825/]
[rospy.impl.masterslave][INFO] 2020-11-24 03:31:49,747: _ready: http://192.168.0.191:41825/
[rospy.registration][INFO] 2020-11-24 03:31:49,749: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-11-24 03:31:49,749: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-11-24 03:31:49,848: registered with master
[rospy.rosout][INFO] 2020-11-24 03:31:49,848: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-24 03:31:49,854: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-24 03:31:49,856: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-24 03:31:49,884: topic[/bev/flow_image] adding connection to [http://192.168.0.201:45935/], count 0
[rospy.internal][INFO] 2020-11-24 03:31:49,887: topic[/scan] adding connection to [http://192.168.0.201:41579/], count 0
[rospy.internal][INFO] 2020-11-24 03:31:49,888: topic[/scan] adding connection to [http://192.168.0.201:38893/], count 1
[rospy.internal][INFO] 2020-11-24 03:31:49,889: topic[/start_goal_points] adding connection to [http://192.168.0.201:40621/], count 0
[rospy.internal][INFO] 2020-11-24 03:31:49,894: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:45935/], count 0
[rospy.internal][INFO] 2020-11-24 03:31:49,895: topic[/odom] adding connection to [http://192.168.0.201:41579/], count 0
[rospy.internal][INFO] 2020-11-24 03:31:50,098: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-24 03:31:50,099: topic[/cmd_vel] adding connection to [/bev_flow_estimator], count 0
[rospy.internal][INFO] 2020-11-24 03:31:50,100: topic[/cmd_vel] adding connection to [/gazebo], count 1
[rospy.internal][INFO] 2020-11-24 03:31:50,100: topic[/is_created_scenarios] adding connection to [/episode_manager], count 0
[rospy.core][INFO] 2020-11-24 03:31:52,362: signal_shutdown [atexit]
[rospy.internal][INFO] 2020-11-24 03:31:52,366: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-24 03:31:52,366: topic[/cmd_vel] removing connection to /bev_flow_estimator
[rospy.internal][INFO] 2020-11-24 03:31:52,366: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-11-24 03:31:52,366: topic[/is_created_scenarios] removing connection to /episode_manager
[rospy.internal][INFO] 2020-11-24 03:31:52,367: topic[/bev/flow_image] removing connection to http://192.168.0.201:45935/
[rospy.internal][INFO] 2020-11-24 03:31:52,367: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:45935/
[rospy.internal][INFO] 2020-11-24 03:31:52,367: topic[/odom] removing connection to http://192.168.0.201:41579/
[rospy.internal][INFO] 2020-11-24 03:31:52,367: topic[/start_goal_points] removing connection to http://192.168.0.201:40621/
[rospy.internal][INFO] 2020-11-24 03:31:52,368: topic[/scan] removing connection to http://192.168.0.201:41579/
[rospy.internal][INFO] 2020-11-24 03:31:52,368: topic[/scan] removing connection to http://192.168.0.201:38893/
[rospy.impl.masterslave][INFO] 2020-11-24 03:31:52,368: atexit
[rospy.internal][WARNING] 2020-11-24 03:31:52,370: Unknown error initiating TCP/IP socket to 192.168.0.201:45977 (http://192.168.0.201:45935/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-11-24 03:31:52,371: Unknown error initiating TCP/IP socket to 192.168.0.201:58309 (http://192.168.0.201:41579/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-11-24 03:31:52,371: Unknown error initiating TCP/IP socket to 192.168.0.201:53063 (http://192.168.0.201:38893/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

