[rospy.client][INFO] 2020-11-24 03:33:29,954: init_node, name[/train_3008_1606188809920], pid[3008]
[xmlrpc][INFO] 2020-11-24 03:33:29,954: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-24 03:33:29,955: Started XML-RPC server [http://192.168.0.191:33391/]
[rospy.init][INFO] 2020-11-24 03:33:29,956: ROS Slave URI: [http://192.168.0.191:33391/]
[rospy.impl.masterslave][INFO] 2020-11-24 03:33:29,956: _ready: http://192.168.0.191:33391/
[rospy.registration][INFO] 2020-11-24 03:33:29,957: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-11-24 03:33:29,957: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-11-24 03:33:30,056: registered with master
[rospy.rosout][INFO] 2020-11-24 03:33:30,056: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-24 03:33:30,062: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-24 03:33:30,063: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-24 03:33:30,078: topic[/bev/flow_image] adding connection to [http://192.168.0.201:45935/], count 0
[rospy.internal][INFO] 2020-11-24 03:33:30,094: topic[/start_goal_points] adding connection to [http://192.168.0.201:40621/], count 0
[rospy.internal][INFO] 2020-11-24 03:33:30,095: topic[/scan] adding connection to [http://192.168.0.201:41579/], count 0
[rospy.internal][INFO] 2020-11-24 03:33:30,098: topic[/scan] adding connection to [http://192.168.0.201:38893/], count 1
[rospy.internal][INFO] 2020-11-24 03:33:30,102: topic[/odom] adding connection to [http://192.168.0.201:41579/], count 0
[rospy.internal][INFO] 2020-11-24 03:33:30,104: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:45935/], count 0
[rospy.internal][INFO] 2020-11-24 03:33:30,230: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-11-24 03:33:30,231: topic[/cmd_vel] adding connection to [/bev_flow_estimator], count 1
[rosout][ERROR] 2020-11-24 03:33:30,247: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:30,281: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rospy.internal][INFO] 2020-11-24 03:33:30,328: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-24 03:33:30,330: topic[/is_created_scenarios] adding connection to [/episode_manager], count 0
[rosout][ERROR] 2020-11-24 03:33:30,487: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:30,520: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:30,719: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:30,753: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:30,949: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:30,982: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:31,183: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:31,216: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:31,415: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:31,450: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:31,648: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:31,678: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:31,877: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:31,908: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:32,106: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:32,134: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:32,329: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:32,362: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:32,559: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:32,591: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:32,786: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rosout][ERROR] 2020-11-24 03:33:32,818: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f89a3df91f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    if msg.ranges[i] != float('inf') and msg.ranges[i] is not None and msg.ranges[i] is not types.NoneType:
AttributeError: module 'types' has no attribute 'NoneType'

[rospy.core][INFO] 2020-11-24 03:33:32,881: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-11-24 03:33:32,886: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-24 03:33:32,886: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-11-24 03:33:32,887: topic[/cmd_vel] removing connection to /bev_flow_estimator
[rospy.internal][INFO] 2020-11-24 03:33:32,887: topic[/is_created_scenarios] removing connection to /episode_manager
[rospy.internal][INFO] 2020-11-24 03:33:32,888: topic[/bev/flow_image] removing connection to http://192.168.0.201:45935/
[rospy.internal][INFO] 2020-11-24 03:33:32,888: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:45935/
[rospy.internal][INFO] 2020-11-24 03:33:32,889: topic[/odom] removing connection to http://192.168.0.201:41579/
[rospy.internal][INFO] 2020-11-24 03:33:32,889: topic[/start_goal_points] removing connection to http://192.168.0.201:40621/
[rospy.internal][INFO] 2020-11-24 03:33:32,889: topic[/scan] removing connection to http://192.168.0.201:41579/
[rospy.internal][INFO] 2020-11-24 03:33:32,890: topic[/scan] removing connection to http://192.168.0.201:38893/
[rospy.impl.masterslave][INFO] 2020-11-24 03:33:32,890: signal-2
[rospy.internal][WARNING] 2020-11-24 03:33:32,891: Unknown error initiating TCP/IP socket to 192.168.0.201:58309 (http://192.168.0.201:41579/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-11-24 03:33:33,372: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-24 03:33:33,414: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-24 03:33:33,438: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-24 03:33:33,468: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-24 03:33:33,515: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-24 03:33:33,541: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-24 03:33:33,560: signal_shutdown [atexit]
